spring.application.name=API-GATEWAY
server.port=8080
#LOGGING
logging.level.root=INFO
#appender consola
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%highlight(%-5level)] [%cyan(%thread)][%X{traceId:-}-%X{spanId:-}] %magenta(%logger{15}) -%msg%n
eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.cloud.gateway.server.webmvc.routes[0].id=MSVC-USERS
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MSVC-USERS
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.server.webmvc.routes[1].id=MSVC-COURSES
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MSVC-COURSES
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/cursos/**
spring.cloud.gateway.server.webmvc.routes[2].id=OAUTH-SERVER
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://OAUTH-SERVER
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/oauth2/**,/login,/.well-known/**
