spring.application.name=MSVC-COURSES
server.port=9002

#LOGGING
logging.level.root=INFO

#appender consola
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%highlight(%-5level)] [%cyan(%thread)][%X{traceId:-}-%X{spanId:-}] %magenta(%logger{15}) -%msg%n



spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#DATABASE CONNECTION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
#spring.jpa.database-platform=${DB_PLATFORM}
#spring.jpa.properties.hibernate.dialect=${DB_PLATFORM}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=${EUREKA_URL}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH_JWK_SET_URI}
